grails-app/domain/com/grailskit/User.groovy
package com.grailskit

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

	private static final long serialVersionUID = 1

	transient springSecurityService

	String username
	String password
	String email
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this)*.role
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password') && password!="" && password!=null) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}

	static transients = ['springSecurityService']

	static constraints = {
		password nullable:true, blank: false, password: true
		username blank: false, unique: true
		email nullable: true, blank: true, unique: true
	}

	static mapping = {
		password column: '`password`'
	}

	String toString() {
		return this.username ?: "n/a"
	}
}

grails-app/controllers/com/grailskit/admin/UserController.groovy
package com.grailskit

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserController {

	static namespace="admin"

	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def index(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		def ul = User.createCriteria().list(max:params.max, offset: params.offset ?: 0) {
			if(session.userSearch)
			{
				or {
					ilike('username','%'+session.userSearch+'%')
					ilike('email','%'+session.userSearch+'%')
				}
			}
		}
		respond ul, model:[search:session?.userSearch ?: null, userCount: ul.totalCount]
	}

	def show(User user) {
		respond user
	}

	def create() {
		respond new User(params), model:[userRoles:[], roles:Role.findAll()]
	}

	@Transactional
	def save(User user) {
		if (user == null) {
			transactionStatus.setRollbackOnly()
			notFound()
			return
		}

		if (user.hasErrors()) {
			transactionStatus.setRollbackOnly()
			respond user.errors, view:'create'
			return
		}

		user.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.username])
				redirect action:"index", method:"GET"
			}
			'*' { respond user, [status: CREATED] }
		}
	}

	def edit(User user) {
		def userRoles = UserRole.findAllByUser(user)
		respond user, model:[userRoles:userRoles, roles:Role.findAll()]
	}

	@Transactional
	def update(User user) {
		if (user == null) {
			transactionStatus.setRollbackOnly()
			notFound()
			return
		}

		def oldpassword
		if(user.password=="" || user.password==null) {
			 oldpassword = user.getPersistentValue('password')
		}
		user.clearErrors()
		// we might not have a password passed in, so
		// 1. don't change previous password
		// don't validate if a password is passed in or not
		def props = User.getConstrainedProperties().collect{ it->
			it.key!="password" ? it : null
		}
		if(oldpassword)
		{
			user.password = oldpassword
		}
		user.validate(props)

		UserRole.removeAll(user)
		params.role.each { it->
			if(it.value=="on"){
				UserRole.create(user, Role.get(it.key?.toLong()))
			}
		}

		if (user.hasErrors()) {
			transactionStatus.setRollbackOnly()
			respond user.errors, view:'edit'
			return
		}

		user.save flush:true


		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
				redirect action:"index", method:"GET"
			}
			'*'{ respond user, [status: OK] }
		}
	}

	@Transactional
	def delete(User user) {

		if (user == null) {
			transactionStatus.setRollbackOnly()
			notFound()
			return
		}

		user.delete flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), user.id])
				redirect action:"index", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}

	protected void notFound() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
				redirect action: "index", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}

	def search()
	{
		if(params.clearSearch)
		{
			session.userSearch = null
		} else {
			session.userSearch = params.search
		}
		redirect(action:"index")
	}
}

grails-app/views/admin/user/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="${gspLayout}" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="create-user" class="content scaffold-create" role="main">
            <content tag="adminHeader">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            </content>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form action="save">
                <div class="nav-tabs">
                    <ul class="nav nav-tabs">
                       <li class="active">
                           <a href="#usertab" data-toggle="tab">Info</a>
                       </li>
                        <li class="">
                            <a href="#userroles" data-toggle="tab">Roles</a>
                        </li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div class="tab-pane active" id="usertab">
                        <fieldset class="form">
                            <f:all bean="user"/>
                        </fieldset>

                    </div>
                    <div class="tab-pane" id="userroles">
                        <g:each in="${roles?.sort{it.authority}}" var="role">
                            <p>
                                <g:checkBox name="role.${role.id}"
                                            value="on"
                                            checked="${userRoles.find{it.role==role}?.role?.id}"
                                ></g:checkBox>
                                <label for="role.${role.id}">
                                    ${role.authority}
                                </label>
                            </p>
                        </g:each>
                    </div>
                </div>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/admin/user/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="${gspLayout}" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="edit-user" class="content scaffold-edit" role="main">
            <content tag="adminHeader">
                <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            </content>
            <g:hasErrors bean="${this.user}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.user}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.user}" method="PUT">
                <g:hiddenField name="version" value="${this.user?.version}" />
                <div class="nav-tabs">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#usertab" data-toggle="tab">Info</a>
                        </li>
                        <li>
                            <a href="#userroles" data-toggle="tab">Roles</a>
                        </li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div class="tab-pane active" id="usertab">
                        <fieldset class="form">
                            <f:all bean="user"/>
                        </fieldset>

                    </div>
                    <div class="tab-pane" id="userroles">

                        <g:each in="${roles?.sort{it.authority}}" var="role">
                            <p>
                            <g:checkBox name="role.${role.id}"
                                value="on"
                                        checked="${userRoles.find{it.role==role}?.role?.id}"
                            ></g:checkBox>
                            <label for="role.${role.id}">
                            ${role.authority}
                            </label>
                            </p>
                        </g:each>
                    </div>
                </div>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/admin/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="${gspLayout}" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="list-user" class="content scaffold-list" role="main">
            <content tag="adminHeader">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            </content>
            <g:form method="post" action="search">
                Search for: <g:textField name="search" value="${search ?: ''}"/>
                <g:if test="${search}">
                <g:submitButton class="btn btn-info btn-sm" name="clearSearch" value="Clear"/>
                </g:if>
                <g:submitButton class="btn btn-info btn-sm" name="searchButton" value="Search"/>
            </g:form>
            <hr/>
            <f:table collection="${userList}"
            properties="${['username','email']}"
            />

            <div class="pagination">
                <g:paginate total="${userCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/admin/user/search.gsp
<html>
<head>
	<meta name="layout" content="${gspLayout}"/>
	<s2ui:title messageCode='spring.security.ui.user.search'/>
</head>
<body>
<content tag="adminHeader">
	User search
</content>
<div>
	<s2ui:formContainer type='search' beanType='user'>
		<s2ui:searchForm colspan='4'>
			<tr>
				<td><g:message code='user.username.label' default='Username'/>:</td>
				<td colspan="3"><g:textField name='username' size='50' maxlength='255' autocomplete='off' value='${username}'/></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td><g:message code='spring.security.ui.search.true'/></td>
				<td><g:message code='spring.security.ui.search.false'/></td>
				<td><g:message code='spring.security.ui.search.either'/></td>
			</tr>
			<tr>
				<td><g:message code='user.enabled.label' default='Enabled'/>:</td>
				<g:radioGroup name='enabled' labels="['','','']" values='[1,-1,0]' value='${enabled ?: 0}'>
					<td><%=it.radio%></td>
				</g:radioGroup>
			</tr>
			<tr>
				<td><g:message code='user.accountExpired.label' default='Account Expired'/>:</td>
				<g:radioGroup name='accountExpired' labels="['','','']" values='[1,-1,0]' value='${accountExpired ?: 0}'>
					<td><%=it.radio%></td>
				</g:radioGroup>
			</tr>
			<tr>
				<td><g:message code='user.accountLocked.label' default='Account Locked'/>:</td>
				<g:radioGroup name='accountLocked' labels="['','','']" values='[1,-1,0]' value='${accountLocked ?: 0}'>
					<td><%=it.radio%></td>
				</g:radioGroup>
			</tr>
			<tr>
				<td><g:message code='user.passwordExpired.label' default='Password Expired'/>:</td>
				<g:radioGroup name='passwordExpired' labels="['','','']" values='[1,-1,0]' value='${passwordExpired ?: 0}'>
					<td><%=it.radio%></td>
				</g:radioGroup>
			</tr>
		</s2ui:searchForm>
	</s2ui:formContainer>
	<g:if test='${searched}'>
	<div class="list">
		<table class="table table-hover">
			<thead>
			<tr>
				<s2ui:sortableColumn property='username' titleDefault='Username'/>
				<s2ui:sortableColumn property='enabled' titleDefault='Enabled'/>
				<s2ui:sortableColumn property='accountExpired' titleDefault='Account Expired'/>
				<s2ui:sortableColumn property='accountLocked' titleDefault='Account Locked'/>
				<s2ui:sortableColumn property='passwordExpired' titleDefault='Password Expired'/>
			</tr>
			</thead>
			<tbody>
			<g:each in='${results}' status='i' var='user'>
				<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
					<td><g:link action='edit' id='${user.id}'>${uiPropertiesStrategy.getProperty(user, 'username')}</g:link></td>
					<td><s2ui:formatBoolean bean='${user}' name='enabled'/></td>
					<td><s2ui:formatBoolean bean='${user}' name='accountExpired'/></td>
					<td><s2ui:formatBoolean bean='${user}' name='accountLocked'/></td>
					<td><s2ui:formatBoolean bean='${user}' name='passwordExpired'/></td>
				</tr>
			</g:each>
			</tbody>
		</table>
	</div>
	<s2ui:paginate total='${totalCount}'/>
	</g:if>
</div>
<s2ui:ajaxSearch paramName='username'/>
<script>
	$(document).ready(function(){
		$("#searchButton").addClass("btn btn-info");
	});
</script>
</body>
</html>

grails-app/views/admin/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="${gspLayout}" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <div id="show-user" class="content scaffold-show" role="main">
            <content tag="adminHeader">
                <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            </content>
            <f:display bean="user" />
            <g:form resource="${this.user}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.user}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>